### ISSUE TITLE
Mailbox

### ISSUE THREAD

**Issue by Braveo** [Miziziziz/Retro3DGraphicsCollection#1]
Don't know if the polygon count may be a bit high for PS1 style graphics, but it might be worth having:

[https://opengameart.org/content/low-poly-textured-mailbox](url)

**Comment by Miziziziz** [comment]
yeah that'll work, thanks!

**Comment by Miziziziz** [comment]
can you add links specifying where you got the textures from and the licensing info for those sites? If you got them from non public domain sources you'll have to reupload to itch as well

**Comment by Braveo** [comment]
I made all the textures from scratch, so there's no worry here 👍
