### ISSUE TITLE
Modern Weapons Pack

### ISSUE THREAD

**Issue by AceX6** [Miziziziz/Retro3DGraphicsCollection#10]
Here's a set of modern weapons I've made. All textures were taken from texturer.com

https://ace-x6.itch.io/modern-weapons-ps1-style

**Comment by Miziziziz** [comment]
nice addition! However on your itch page can you edit the first part to say "Textures from texturer.com, license info here: http://texturer.com/terms/"

**Comment by AceX6** [comment]
Changes made
