### ISSUE TITLE
Three barrels (regular, explosive, corrosive) and a rigged crow

### ISSUE THREAD

**Issue by itsPeetah** [Miziziziz/Retro3DGraphicsCollection#11]
The crows wings are a little disjointed but you can easily animate it not to look like so.
Base metal textures for the barrels from https://textures.com, everything else is made by me.

Link: https://punkpebblestudio.itch.io/low-poly-ps1-style-game-assets

**Comment by Miziziziz** [comment]
nice pack, but can you edit the description to include license info? just say the models are cc0 (if you made them) and provide links to where you got the textures from

**Comment by itsPeetah** [comment]
You're totally right, updated

**Comment by Miziziziz** [comment]
can you put the license info on the itch page as well?

**Comment by itsPeetah** [comment]
done

**Comment by Miziziziz** [comment]
nice thanks

**Comment by Miziziziz** [comment]
hey a password is required to view this now, can you fix that?
