### ISSUE TITLE
European small family car (1960s and 1970s)

### ISSUE THREAD

**Issue by ggbotnet** [Miziziziz/Retro3DGraphicsCollection#13]
3D model and textures are made by me.

https://ggbot.itch.io/psx-style-car

Small video (22 sec.)
https://www.youtube.com/watch?v=BRNg7bIGKeg

**Comment by Miziziziz** [comment]
nice asset thanks! Just to clarify first, did you made the textures yourself or get them from a site?

**Comment by ggbotnet** [comment]
The texture is hand painted and then scaled down to 128x128.
