### ISSUE TITLE
I made some fish and a raven, my issue with this project is that I think it's a brilliant idea and I'm gladly contributing to it.

### ISSUE THREAD

**Issue by CokeEnthusiast** [Miziziziz/Retro3DGraphicsCollection#14]
https://cokeenthusiast.itch.io/ps1-style-fish

**Comment by Scoppio** [comment]
If you prefer to have a single file for all, you can zip all and upload the zip

**Comment by Miziziziz** [comment]
nice fish thanks! (also can you put all the files in a zip folder and upload that to the itch page? will be a lot easier for people to download)
