### ISSUE TITLE
Warehouse assets, Rigged Knight

### ISSUE THREAD

**Issue by Scoppio** [Miziziziz/Retro3DGraphicsCollection#15]
So... I made a knight, with rigging, in your course at Udemy, so why not share it? https://scoppio.itch.io/fullplate-armor-knight
Also, did some warehouse things - forklift, chain and hook, and a 200L barrel - https://scoppio.itch.io/forklift-chain-hook-and-barrel

All under cc0, textures credited in all files even those I did myself, released on itch, as $0 or donate method for download.

**Comment by Miziziziz** [comment]
can you add the texture info to the itch pages as well?

**Comment by Scoppio** [comment]
Done :D

**Comment by Miziziziz** [comment]
thanks! added
