### ISSUE TITLE
Pair of Barrels

### ISSUE THREAD

**Issue by PSI-Boredom-Omega** [Miziziziz/Retro3DGraphicsCollection#17]
I think I saw someone else already add some barrels to this but I did think that these would fit just fine with the rest of the collection.

https://psi-boredom-omega.itch.io/ps1-styled-barrels

**Comment by Miziziziz** [comment]
looks cool, thanks!

**Comment by PSI-Boredom-Omega** [comment]
No problem! Glad to contribute :)

**Comment by Miziziziz** [comment]
btw please submit an issue if you change your itch username again as that breaks links
