### ISSUE TITLE
uploaded some of my models for use!

### ISSUE THREAD

**Issue by studioNOKOI** [Miziziziz/Retro3DGraphicsCollection#2]
hope they're good enough :D 
https://opengameart.org/content/miscellaneous-low-poly-objects

**Comment by Miziziziz** [comment]
they look good, thanks!

**Comment by Miziziziz** [comment]
can you add links specifying where you got the textures from and the licensing info for that site? You'll have to reupload to itch probably if it's not from a public domain source

**Comment by studioNOKOI** [comment]
this is months late (oops) but here ya go https://studionokoi.itch.io/low-poly-assets-1

**Comment by Miziziziz** [comment]
thanks!
