### ISSUE TITLE
Classic64 Asset Library 

### ISSUE THREAD

**Issue by iamcraigsnedeker** [Miziziziz/Retro3DGraphicsCollection#22]
A slowly growing asset library of N64/PS1 style textures and models released under a CC0. 
https://craigsnedeker.itch.io/classic64-asset-library

**Comment by Miziziziz** [comment]
wow, incredible collection! Thanks for sharing

**Comment by iamcraigsnedeker** [comment]
> wow, incredible collection! Thanks for sharing

Thanks! Also love this collection you're putting together :)
