### ISSUE TITLE
Double chairs

### ISSUE THREAD

**Issue by amarogamedev** [Miziziziz/Retro3DGraphicsCollection#23]
Not sure if this is the right place to send this, but seems like you've pasted the same asset twice on the same list. I wonder if there's a reason for it or you just did it accidentally.

![image](https://user-images.githubusercontent.com/80685926/111341729-8b76e100-8658-11eb-94bf-cb92a7a41e84.png)

**Comment by Miziziziz** [comment]
oh woops, thanks for pointing that out
