### ISSUE TITLE
German Police Officer

### ISSUE THREAD

**Issue by stephanroberts** [Miziziziz/Retro3DGraphicsCollection#25]
First, sorry did it first on the wrong way :-(
I am a totally noob on GitHub ...

but here we go again :-D

So 
https://stephrobertgames.itch.io/german-police-officer

here are my Police officer ... I will update it by time.
Currently its only a full textured Model (textures all by myself)
Later it will be rigged and also I have some Ideas for animations

Had a lot of Fun by creating this Character, so I think there will be more in the Future :-)

**Comment by Miziziziz** [comment]
nice, thanks for adding! Good to get some characters
