### ISSUE TITLE
Urban Kit (100 models)

### ISSUE THREAD

**Issue by KenneyNL** [Miziziziz/Retro3DGraphicsCollection#26]
Hey! Created a package of 100 models including custom made textures, all CC0. The files come in 5 different 3D formats which should be compatible with most game engines.

https://kenney.nl/assets/retro-urban-kit
https://opengameart.org/content/retro-urban-kit (alternative download)

**Comment by Iglum** [comment]
Thank you KenneyNL! you are the man! 
Gonna space them out on a grid in my .blend file :) gonna make some small animations and scenes.

**Comment by Miziziziz** [comment]
siiiick collection
