### ISSUE TITLE
New Police officer

### ISSUE THREAD

**Issue by stephanroberts** [Miziziziz/Retro3DGraphicsCollection#29]
Hey there me again,

I create a new german police officer, this time I create a small set also with animations.
This version Fits better for PSX - Like design, I think, 
But the Old one will also be online, maybe someone could also need the old ;-).

But now I think I am on a good way ... next time it will be a other character :-D

https://stephrobertgames.itch.io/german-police-officer-set

**Comment by Miziziziz** [comment]
looks cool! just to confirm, you handmade the textures for everything?

**Comment by stephanroberts** [comment]
Yes all Textures are Handmade, the texture for the Car are recreated by the Textures based on the original version of the Car ... I only redesigned it an paint over. But the Original Car from GGBot: https://ggbot.itch.io/psx-style-cars is also under cc0 licence

**Comment by Miziziziz** [comment]
added thanks!
