### ISSUE TITLE
Sea Shack

### ISSUE THREAD

**Issue by Agroithien** [Miziziziz/Retro3DGraphicsCollection#32]
I watch this tutorial by "Grant Abbitt" 
https://www.youtube.com/watch?v=Jmir2bDpZA4&list=PLn3ukorJv4vsIOjZoMToZusH2uOyjCu6G

and made this:
https://agroithien.itch.io/sea-shack

**Comment by Miziziziz** [comment]
looks nice, but doesn't fit the retro graphics aesthetic as there aren't any low res textures on it
