### ISSUE TITLE
Very basic "Menu System" for Game Jams

### ISSUE THREAD

**Issue by Agroithien** [Miziziziz/Retro3DGraphicsCollection#34]
This "Menu System" is made by me for a game jam which is very basic in terms of design, graphics, animation, and sound.
I'm uploading that entire project and as a package (MM V.unitypackage) to itch.io and my git hub as well...

**Important**
**Some assets listed have dependencies that are part of Package Manager packages and these cannot be exported, so those references will be lost if those packages are not present in the importing project.**

**You have to have this before importing the MM V asset.** 
**Which can be found in the package manager i.e, is in package Unity UI.**

The "Audio Manager" script is from "Brakeys" and everything else is coded and designed by me...
and it has a GNU GPLv3 and CC0 license so no need to asking

I consider it as **Menu Game Jam edition...**

**Links:**
itch.io: https://itch.io/game/edit/1020712
GitHub: https://github.com/Agroithien/BasicMenuSystem

**Comment by Miziziziz** [comment]
thanks for submitting, but this repo is for 3d assets, not code

**Comment by Agroithien** [comment]
So... should I remove it or keep it...
