### ISSUE TITLE
Two Dieselpunk Tanks

### ISSUE THREAD

**Issue by abandon-hope** [Miziziziz/Retro3DGraphicsCollection#39]
Two dieselpunk tanks I made, for your perusal - don't know if they might fit in fantasy/scifi/contemporary?

16 colors per 256*256 texture, low-poly models, hope it's a fit somewhere here.

https://chilly-durango.itch.io/2dieselpunktanks
[Dieselpunk Tanks.zip](https://github.com/Miziziziz/Retro3DGraphicsCollection/files/6856975/Dieselpunk.Tanks.zip)

**Comment by Miziziziz** [comment]
nice thanks!
