### ISSUE TITLE
More "Retro-Style" shaders

### ISSUE THREAD

**Issue by dukemagus** [Miziziziz/Retro3DGraphicsCollection#43]
The quality and ammount of features vary wildly, but they're still focusing on the same subject and have a compatible license to the collection

Unity: Built-in Renderer (most are old, but so is the pipeline)

- https://github.com/FireFlyForLife/Retro3DPipeline Forked from the Keijiro implementation (Keijiro works for Unity Japan). It's a work made on top of his previous retro3d shader (https://github.com/keijiro/Retro3D) and the license is "You can use the shader for whatever you want.". I think the license is the same
- https://github.com/brunurd/psx_retroshader Forked from dsoft20 repo (MIT License)
https://tpotssl.itch.io/cathoder (MIT License)

Unity: URP
- https://github.com/Cyanilux/URP_RetroCRTShader (MIT License)
- https://github.com/StefanJo3107/ASCII-Rendering-Shader-in-Unity (MIT License) If you consider old nethack games and ascII art retro...

Godot
- https://github.com/Ahopness/GodotRetro (CC0 1.0 license)
- https://github.com/MenacingMecha/godot-psx-style-demo (MIT License)
- https://github.com/samuelbigos/godot_dither_shader (MIT License) Dither by itself isn't "retro", but it's a building block for pc98 or early dos style graphics
- https://godotshaders.com/shader/vhs-and-crt-monitor-effect/ (CC0 License)
- https://godotshaders.com/shader/ps1-shader/ &  https://godotshaders.com/shader/ps1-post-processing/ (CC0 License) Use both together. Doesn't support transparent surfaces

**Comment by Miziziziz** [comment]
thanks, I'll just put a link to this rather than a bunch of individual links

**Comment by Alvarden15** [comment]
Hello there. Not sure if you are still open to suggestion, but i wanted to share a retro asset for Unity URP:
https://github.com/Math-Man/URP-PSX-FORKED
