### ISSUE TITLE
Low-Poly Glock 17

### ISSUE THREAD

**Issue by mextie-dev** [Miziziziz/Retro3DGraphicsCollection#44]
A low-poly PSX style Glock 17. Download includes Blender file + Collada, FBX, GLB, OBJ, and STL versions of the model. [Textures are from Wikimedia Commons.](https://commons.wikimedia.org/wiki/File:Glock_17_2nd_Gen.jpg)

https://mextie.itch.io/low-poly-glock

**Comment by Miziziziz** [comment]
thanks, added!
