### ISSUE TITLE
I Would Like To Contribute!

### ISSUE THREAD

**Issue by PrinterIsNotFound** [Miziziziz/Retro3DGraphicsCollection#53]
Hey, I made a PS1/PSX Model of a vase. The model is free on itch.io ( https://printer-not-found.itch.io/psx-pot )

I made the model and have put it under CC0 license.
I got the texture from Texturer.com (here is a link: http://texturer.com/)

![PreviewImage (2)](https://user-images.githubusercontent.com/75360384/162566118-1d3550cf-b04f-4834-999b-588c450243ea.png)

**Comment by Miziziziz** [comment]
added thanks!
