### ISSUE TITLE
Retro Radio

### ISSUE THREAD

**Issue by laleksic** [Miziziziz/Retro3DGraphicsCollection#56]
Hi,
I made a low poly retro radio: https://aleksicluka.itch.io/low-poly-retro-radio

![preview_hires](https://user-images.githubusercontent.com/22757092/178163005-1682027d-257f-4605-bb79-12a2ab429ab1.png)
![preview_lores](https://user-images.githubusercontent.com/22757092/178163008-b32be409-673d-4761-8eb1-2c29a1cca77a.png)

**Comment by Miziziziz** [comment]
added thanks!
