### ISSUE TITLE
Pegasus and Chimera Statues

### ISSUE THREAD

**Issue by Hynes-J** [Miziziziz/Retro3DGraphicsCollection#6]
Hey, thought this was a great idea and wanted to add some stuff, will keep adding future stuff as I create it, these are just a test really but plan on using them in my own project.

https://tellyhead.itch.io/pegasus-and-chimera-retro-3d-models

**Comment by Miziziziz** [comment]
These are cool! Can you add license info on the page though? Just a note saying its cc0 license

**Comment by Miziziziz** [comment]
can you add links specifying where you got the textures from and the licensing info for those sites?
