### ISSUE TITLE
Sawed double barrel shotgun

### ISSUE THREAD

**Issue by Levrault** [Miziziziz/Retro3DGraphicsCollection#69]
Hi,

I created this shotgun https://levrault.itch.io/low-poly-double-shotgun . It's already rigged and textured.

Texture has been took from [www.irongatearmory.com](http://www.irongatearmory.com/)
with the permission of the owner.

![image](https://github.com/Miziziziz/Retro3DGraphicsCollection/assets/1162446/51a8eefa-6d95-4e9b-a31b-eedbee56b215)

**Comment by Miziziziz** [comment]
Thanks for submitting, but that image of an email doesn't work as a free commercial use license of the texture, sorry

**Comment by Levrault** [comment]
I understand, I through having permission from the author could be enough (asked in my original email that it will be use under a CC0 license) but it's seems more complicated. I will try to re-texture my model with image that is already under fair use if I found one.
