### ISSUE TITLE
psx houseplants

### ISSUE THREAD

**Issue by valsekamerplant** [Miziziziz/Retro3DGraphicsCollection#71]
hey it's me tophatpanda but my name changed on itch.io
here are some houseplants

https://valsekamerplant.itch.io/psx-style-house-plants-and-pots

and 
modular hedges: https://tophatpanda.itch.io/psx-style-hedges
modular fences: https://tophatpanda.itch.io/psx-style-fences
Modular Vents: https://tophatpanda.itch.io/psx-style-modular-vents
retro modular dungeon tileset: https://tophatpanda.itch.io/retro-modular-dungeon-tileset

will probably need to update to 
https://valsekamerplant.itch.io/{item}

**Comment by Miziziziz** [comment]
added thanks!
