### ISSUE TITLE
psx paintings

### ISSUE THREAD

**Issue by Redd56** [Miziziziz/Retro3DGraphicsCollection#72]
found these last week https://pizzadoggy.itch.io/psx-paintings
doesnt say cc0 but instead says no credit required. 

"Credit is not required!

This asset pack can be used for any commercial or non-commercial project and you may modify it in any way you choose to suit your needs and recreate your imagination. It cannot be resold/redistributed in a form of game assets, even if modified, but it's absolutely okay to share it privately within a development team. "

unsure if it fits withing the feel of the project

**Comment by Miziziziz** [comment]
nah don't want to add anything without a clear license
