### ISSUE TITLE
Fix link to "Metal and Explosive Barrels."

### ISSUE THREAD

**Issue by xiiixvv** [Miziziziz/Retro3DGraphicsCollection#75]
Hello, was going under a rebrand but I ended up breaking the old link of mine on here. Was wanting to fix that and it's surprising that this is still being updated two or so years later so I could have a good chance at getting this rectified quickly.

Just change
`https://alium-realis.itch.io/ps1-styled-barrels `
to
`https://xiiixvv.itch.io/ps1-styled-barrels`

Thanks in advance :3

**Comment by Miziziziz** [comment]
fixed thanks!
