### ISSUE TITLE
Stiff Old Chair !

### ISSUE THREAD

**Issue by SamyBencherif** [Miziziziz/Retro3DGraphicsCollection#8]
I am excited to present to you what I am hoping will be the first chair / furniture of your collection.

![chair-preview-small](https://user-images.githubusercontent.com/10871454/110086442-5f0dbb80-7d60-11eb-814c-cf5c4c2c2c10.png)

https://samybencherif.itch.io/uncomfortable-looking-yellow-chair

I created the model geometry and texture for this and left a note declaring this asset as part of the public domain under the CC0 license.

**Comment by Miziziziz** [comment]
nice thanks! Just to be clear, you made the textures from scratch or got them from cc0 sources right?

**Comment by SamyBencherif** [comment]
That is correct!
